locale = "pt-BR"
label = "Português"
weight = 1
title = "MSMelo.Blog"

[params]
  languageDirection = "ltr"
  DateFormat = ":date_long"
  description = "Escritor, desenhista, detetive de códigos. Crônicas, contos e causos com malemolência baiana."
  keywords = ["crônicas", "contos", "literatura", "Bahia", "M. S. Melo"]
