[[main]]
name = "Blog"
pageRef = "posts"
weight = 1

[[main]]
name = "Livros"
pageRef = "livros"
weight = 2

[[main]]
name = "Contos"
url = "https://escritos.msmelo.blog/contos"
weight = 3

[[main]]
name = "Newsletter"
url = "https://marciosmelo.substack.com"
weight = 4

[[main]]
name = "Blogroll"
pageRef = "/blogroll"
weight = 5

[[main]]
name = "Sobre"
pageRef = "/sobre"
weight = 6

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Assine minha newsletter"
  url = "https://marciosmelo.substack.com"
  weight = 20

[[footer]]
  name = "Assine o RSS"
  url = "/index.xml"
  weight = 30
