colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "posts" ]
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "/img/gamboa.jpg"
defaultFeaturedImage = "/img/blog.jpg"
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
layout = "fixed"
showAuthor=true

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "/img/porto.jpg"
showAuthor = true
showRecent = true
showRecentItems = "10"
showMoreLink = true
showMoreLinkDest = "posts"
cardView = true
cardViewScreenWidth = true
layoutBackgroundBlur = true

[article]
showDate = true
showViews = false
showLikes = true
showDateUpdated = true
showAuthor = true
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
#editURL = "https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 6
showTaxonomies = true
showAuthorsBadges = true
showWordCount = false
sharingLinks = [ "twitter", "whatsapp", "telegram", "pinterest", "facebook", "email" ]
showZenMode = false

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = true
constrainItemsWidth = true

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = true
cardViewScreenWidth = false
  
[firebase]
  apiKey = "AIzaSyB5skqvTGFBj1zNMQugvvy-U0aMUIF67ck"
  authDomain = "msmelo-751ee.firebaseapp.com"
  projectId = "msmelo-751ee"
  storageBucket = "msmelo-751ee.appspot.com"
  messagingSenderId = "480375533959"
  appId = "1:480375533959:web:aac02cce61ea6ad3c3e322"
  measurementId = "G-PWQT6Y8M01"