paginate = 10
mainSections = ["posts"]
description = "Escritor, desenhista, detetive de códigos."

[[social]]
  name = "Mastodon"
  url = "https://bolha.one/@msmelo"

[[social]]
  name = "Bluesky"
  url = "https://bsky.app/profile/marciosmelo.bsky.social"

[[social]]
  name = "GitHub"
  url = "https://github.com/marciosmelo"

[[social]]
  name = "RSS"
  url = "/index.xml"
