name: Deploy to Hostinger (SFTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLEAN_SLATE: 'false'   # já foi validado; manter 'false' para deploy incremental
      SFTP_PORT: '65002'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.150.0'
          extended: true

      - name: Build
        run: |
          echo "[info] Build do Hugo"
          hugo --minify
          ts=$(date -u +%Y%m%d-%H%M%S)
          echo "marker ${ts}" > public/deploy-marker-${ts}.txt
          echo "[info] Marker: deploy-marker-${ts}.txt"
          du -sh public || true

      - name: Limpar remoto (clean slate)
        if: env.CLEAN_SLATE == 'true'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: ${{ env.SFTP_PORT }}
          script: |
            set -e
            echo "[info] Limpando ${{ secrets.HOSTINGER_SSH_REMOTE_DIR }}"
            rm -rf "${{ secrets.HOSTINGER_SSH_REMOTE_DIR }}"/*

      - name: Upload (conteúdo da pasta public para raiz remota)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: ${{ env.SFTP_PORT }}
          # Envia a pasta public inteira mas remove o primeiro nível para não criar subdiretório 'public' remoto
          source: "public/**"
          target: "${{ secrets.HOSTINGER_SSH_REMOTE_DIR }}"
          strip_components: 1

      - name: Summary
        run: |
          marker=$(ls public/deploy-marker-*.txt 2>/dev/null | tail -n1 | xargs -r basename)
          echo "Deploy concluído. CLEAN_SLATE=${CLEAN_SLATE} (use 'true' apenas se quiser limpar tudo no próximo)"
          if [ -n "$marker" ]; then echo "Marker URL: https://msmelo.blog/${marker}"; fi
          echo "Se páginas derem 404 limpe cache do navegador / CDN (se houver)."

